#=====================================================================
# AXI4-Lite peripheral subsystem — front door
#
#   make test                 both smoke benches, Verilator + assertions
#   make test TEST=reg        register slave only
#   make test TEST=mem        memory slave only
#   make test SIM=icarus      functional only; Icarus cannot do SVA
#   make coverage             cover-property counts for both benches
#   make lint                 Verilator -Wall on the RTL
#   make playground PLAY=x    bundle UVM sources (x = hello|rand_smoke|smoke)
#   make clean
#
# Deliberately thin: it wraps scripts/run_sim.sh rather than duplicating
# the flow. Per docs/automation_plan.md, the toolkit proper (regression
# runner, log parser) is a September build; before DVCon this file is the
# only automation, and its job is to make `make test` the thing you type.
#
# September's targets — `make regression`, `make test TEST=axi_smoke_test
# SEED=42` — hang off this same front door once run_regression.py exists.
#=====================================================================

SIM  ?= verilator
TEST ?= all
RTL  := rtl/axi4lite_reg_slave.sv rtl/axi4lite_mem_slave.sv

.PHONY: test coverage lint clean help playground

test:
	@./scripts/run_sim.sh $(SIM) $(TEST)

coverage:
	@./scripts/run_sim.sh verilator $(TEST) --coverage

# One file at a time: linting both together trips MULTITOP, since each
# is a legitimate top in its own right until the interconnect exists.
lint:
	@for f in $(RTL); do \
		echo "  lint $$f"; \
		verilator --lint-only -Wall --timing $$f || exit 1; \
	done
	@echo "lint: clean"

#---------------------------------------------------------------------
# EDA Playground bundling.
#
# Playground has two panes and no file list, so multi-file UVM source has
# to arrive as one paste. This concatenates a named bundle in dependency
# order and emits the uvm_macros include / uvm_pkg import exactly once.
#
# The guard tests for '^import uvm_pkg', not for the word uvm_macros.svh:
# source comments mention that filename, so a looser grep matches a comment
# and silently skips the preamble the bundle actually needs.
#
# UVM cannot be run locally -- neither Icarus nor Verilator supports it --
# so this target only produces the file. Running it is manual, on
# EDA Playground with Cadence Xcelium. See docs/tooling_notes.md.
#---------------------------------------------------------------------
PLAY ?= rand_smoke

PLAY_rand_smoke := tb/agent/axi_transaction.sv tb/agent/axi_sequencer.sv tb/uvm/axi_rand_smoke.sv
PLAY_hello      := tb/uvm/uvm_hello.sv

# The first bundle that needs a DESIGN pane: the driver drives real pins,
# so the interface, the DUT and the bound checker have to be there too.
PLAY_smoke_DESIGN := tb/interface/axi4lite_if.sv rtl/axi4lite_reg_slave.sv \
                     tb/interface/axi4lite_checker_bind.sv
PLAY_smoke        := tb/agent/axi_transaction.sv tb/agent/axi_sequencer.sv \
                     tb/agent/axi_driver.sv tb/agent/axi_master_agent.sv \
                     tb/sequences/axi_seqs.sv tb/env/axi_env.sv \
                     tb/tests/axi_smoke_test.sv tb/tests/tb_top.sv

playground:
	@mkdir -p sim
	@srcs="$(PLAY_$(PLAY))"; \
	 if [ -z "$$srcs" ]; then \
	   echo "unknown bundle '$(PLAY)' -- try hello, rand_smoke or smoke"; exit 2; fi; \
	 out=sim/playground_$(PLAY).sv; \
	 { echo "// GENERATED by 'make playground PLAY=$(PLAY)' -- do not edit."; \
	   echo "// Paste into the EDA Playground TESTBENCH pane."; \
	   if [ -n "$(PLAY_$(PLAY)_DESIGN)" ]; then \
	     echo "// The DESIGN pane takes sim/playground_$(PLAY)_design.sv."; \
	   else echo "// Leave the DESIGN pane empty."; fi; \
	   echo "// Simulator: Cadence Xcelium.  UVM: 1.2.  (Riviera compiles but cannot simulate.)"; \
	   echo "// Sources, in order:"; \
	   for f in $$srcs; do echo "//   $$f"; done; \
	   echo ""; \
	   if ! grep -q '^import uvm_pkg' $$srcs; then \
	     echo '`include "uvm_macros.svh"'; echo "import uvm_pkg::*;"; echo ""; fi; \
	   for f in $$srcs; do \
	     echo "//================ $$f ================"; cat $$f; echo ""; done; \
	 } > $$out; \
	 echo "wrote $$out ($$(wc -l < $$out) lines) -- TESTBENCH pane"; \
	 dsrcs="$(PLAY_$(PLAY)_DESIGN)"; \
	 if [ -n "$$dsrcs" ]; then \
	   dout=sim/playground_$(PLAY)_design.sv; \
	   { echo "// GENERATED by 'make playground PLAY=$(PLAY)' -- do not edit."; \
	     echo "// Paste into the EDA Playground DESIGN pane."; \
	     for f in $$dsrcs; do echo "//   $$f"; done; echo ""; \
	     for f in $$dsrcs; do \
	       echo "//================ $$f ================"; cat $$f; echo ""; done; \
	   } > $$dout; \
	   echo "wrote $$dout ($$(wc -l < $$dout) lines) -- DESIGN pane"; \
	 fi

clean:
	@rm -rf sim/*.out sim/*.vcd sim/*.dat sim/cov_annotated sim/playground_*.sv
	@rm -rf $${TMPDIR:-/tmp}/axi4lite_vbuild
	@echo "clean: done"

help:
	@sed -n '4,11p' Makefile | sed 's/^# \?//'
